// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ0eeLcrEGVrTbrmftpI4aSX2SCzNP7n4',
    appId: '1:545494681366:web:f54382a518adf1805e3237',
    messagingSenderId: '545494681366',
    projectId: 'authtutorial-b0bb5',
    authDomain: 'authtutorial-b0bb5.firebaseapp.com',
    storageBucket: 'authtutorial-b0bb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JOT4B_VKCc429ac24ZQD6GPxw06vAsE',
    appId: '1:545494681366:android:66b11637feab44335e3237',
    messagingSenderId: '545494681366',
    projectId: 'authtutorial-b0bb5',
    storageBucket: 'authtutorial-b0bb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLv4wZ_Wjk6oBVoWhgOUGnMGjJspqvPfA',
    appId: '1:545494681366:ios:024ce7b1577fa7365e3237',
    messagingSenderId: '545494681366',
    projectId: 'authtutorial-b0bb5',
    storageBucket: 'authtutorial-b0bb5.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLv4wZ_Wjk6oBVoWhgOUGnMGjJspqvPfA',
    appId: '1:545494681366:ios:024ce7b1577fa7365e3237',
    messagingSenderId: '545494681366',
    projectId: 'authtutorial-b0bb5',
    storageBucket: 'authtutorial-b0bb5.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ0eeLcrEGVrTbrmftpI4aSX2SCzNP7n4',
    appId: '1:545494681366:web:584a48f1e749fde05e3237',
    messagingSenderId: '545494681366',
    projectId: 'authtutorial-b0bb5',
    authDomain: 'authtutorial-b0bb5.firebaseapp.com',
    storageBucket: 'authtutorial-b0bb5.firebasestorage.app',
  );

}